name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - See CHANGELOG.md for details
          draft: false
          prerelease: false
          
      - name: Update major version tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          git tag -fa v$MAJOR_VERSION -m "Update v$MAJOR_VERSION tag"
          git push origin v$MAJOR_VERSION --force